name: CI

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, ${{ github.event.label.name }}! title-${{ github.event.pull_request.title }}

  build-question:
    if: ${{ github.event.label.name == 'question' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, ${{ github.event.label.name }}! title-${{ github.event.pull_request.title }}
 